"""helixgen-model-id-string -> device NUMERIC model-id reconciliation.

helixgen and the Helix Stadium device name the SAME models with DIFFERENT id
strings, and the device network protocol addresses models by a NUMERIC id.
helixgen's library / ``.hsp`` files speak HX-Edit export model-id STRINGS (e.g.
``HD2_ReverbPlateStereo``, or translated forms like ``HD2_DrvScream808``); the
device modeldefs speak internal strings + numeric ids (e.g.
``HD2_DistScream808Mono`` -> 310). The device-authoring bridge needs to turn a
helixgen model id into the numeric id the device protocol expects.

This module is the pure-stdlib RUNTIME loader over the vendored asset
``_modelmap.json`` (regenerated by ``tools/build_modelmap.py`` from the helixgen
library + device defs + editor UIDefs). It has NO app dependency at runtime and
reads only the vendored json.

Asset shape::

    {
      "map":       {"<helixgen_model_id>": <device_numeric_id>, ...},
      "unmatched": ["<helixgen_model_id>", ...],
      "matches":   {"<helixgen_model_id>": {audit fields}, ...},
      "meta":      {"counts": {...}, "coverage_pct": ..., ...}
    }
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

_DATA_PATH = Path(__file__).with_name("_modelmap.json")


@lru_cache(maxsize=1)
def load_modelmap() -> dict[str, Any]:
    """Load and cache the vendored model-map asset.

    Raises a clear error if ``_modelmap.json`` is absent (regenerate it with
    ``tools/build_modelmap.py``).
    """
    if not _DATA_PATH.exists():
        raise FileNotFoundError(
            f"model-map asset missing: {_DATA_PATH}. "
            "Regenerate it with `python tools/build_modelmap.py`."
        )
    with _DATA_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def device_model_id(helixgen_model_id: str) -> Optional[int]:
    """Device NUMERIC model id for a helixgen model-id string.

    Returns ``None`` when the helixgen model has no confident device match
    (i.e. it is unmatched or unknown). Never raises on a bad key.
    """
    return load_modelmap().get("map", {}).get(helixgen_model_id)


def is_unmatched(helixgen_model_id: str) -> bool:
    """True if the model id was seen in the helixgen library but had no match.

    Distinguishes a known-but-unmatched model from a wholly unknown id (both
    make :func:`device_model_id` return ``None``).
    """
    return helixgen_model_id in set(load_modelmap().get("unmatched", []))


def match_detail(helixgen_model_id: str) -> Optional[dict[str, Any]]:
    """Full audit record for a matched model (method, confidence, device name),
    or ``None`` if unmatched/unknown."""
    rec = load_modelmap().get("matches", {}).get(helixgen_model_id)
    return dict(rec) if rec is not None else None


def coverage() -> dict[str, Any]:
    """Counts + coverage percentage for the map (from the asset's meta)."""
    meta = load_modelmap().get("meta", {})
    counts = dict(meta.get("counts", {}))
    counts["coverage_pct"] = meta.get("coverage_pct")
    return counts
